import {
  User,
  Student,
  Course,
  ClassRoom,
  Enrollment,
  Charge,
  PaymentReceipt,
  CashRegister,
  CashMovement,
  AttendanceRecord,
  Lesson,
  Assessment,
  Grade,
  Assignment,
  Submission,
  AccountingTransaction,
  AuditLog,
  SystemSettings,
  SystemNotification,
} from '../types';

export const INITIAL_SETTINGS: SystemSettings = {
  centerName: 'Think Green Community Center',
  location: 'Cairo, Egypt (مصر)',
  currencySymbol: 'EGP',
  currencyCode: 'EGP',
  enableAutomaticExamGates: true,
  enableAutomaticClassroomGates: true,
  minimumPassingGrade: 60,
  attendanceRequirementPercent: 75,
  rulesConfig: {
    rule1_classroomRequiresFirstPayment: true,
    rule2_exam1RequiresSecondPayment: true,
    rule3_finalExamRequiresFullPayment: true,
  },
};

export const INITIAL_USERS: User[] = [
  {
    id: 'user_super_admin',
    name: 'Eng. Ricky Jorge Castro',
    email: 'ricky@thinkgreen.org',
    role: 'SUPER_ADMIN',
    department: 'Diretoria Executiva & Tecnologia',
    status: 'ACTIVE',
    permissions: ['*'],
    createdAt: '2026-01-01',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_admin',
    name: 'Dr. Magdy Yacoub',
    email: 'admin@thinkgreen.org',
    role: 'ADMINISTRATION',
    department: 'Gestão Geral do Centro',
    status: 'ACTIVE',
    permissions: ['manage_users', 'manage_settings', 'view_reports', 'manage_business_rules', 'view_audit_logs'],
    createdAt: '2026-01-10',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_sec',
    name: 'Mona Abdelrahman',
    email: 'secretaria@thinkgreen.org',
    role: 'SECRETARIAT',
    department: 'Secretaria & Atendimento',
    status: 'ACTIVE',
    permissions: ['view_students', 'create_student', 'edit_student', 'manage_enrollments', 'transfer_classes'],
    createdAt: '2026-01-15',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_fin',
    name: 'Karim Fahmy',
    email: 'financeiro@thinkgreen.org',
    role: 'FINANCE',
    department: 'Financeiro & Tesouraria',
    status: 'ACTIVE',
    permissions: ['view_finance', 'register_payments', 'manage_cash_register', 'issue_receipts', 'manage_payment_plans'],
    createdAt: '2026-01-15',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_acc',
    name: 'Hisham El-Ghazaly',
    email: 'contabilidade@thinkgreen.org',
    role: 'ACCOUNTING',
    department: 'Contabilidade & Controladoria',
    status: 'ACTIVE',
    permissions: ['view_accounting', 'manage_revenues', 'manage_expenses', 'financial_closing', 'export_reports'],
    createdAt: '2026-01-20',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_teacher_1',
    name: 'Professor Lucas',
    email: 'lucas.professor@thinkgreen.org',
    role: 'TEACHER',
    department: 'Corpo Docente Think Garden',
    status: 'ACTIVE',
    permissions: ['view_academic', 'take_attendance', 'grade_assessments', 'publish_material', 'grade_assignment'],
    createdAt: '2026-02-01',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_teacher_2',
    name: 'Prof. Tarek Mansour',
    email: 'tarek.sports@thinkgreen.org',
    role: 'TEACHER',
    department: 'Academia de Futebol',
    status: 'ACTIVE',
    permissions: ['view_academic', 'take_attendance', 'grade_assessments', 'publish_material'],
    createdAt: '2026-02-01',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_student_1',
    name: 'Ahmed Mohamed',
    email: 'ahmed.m@student.thinkgreen.org',
    studentId: 'STU00184',
    role: 'STUDENT',
    department: 'Aluno Think Green',
    status: 'ACTIVE',
    permissions: ['access_lms_student', 'submit_assignment', 'view_own_financials'],
    createdAt: '2026-02-10',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_student_2',
    name: 'Mariam Youssef',
    email: 'mariam.y@student.thinkgreen.org',
    studentId: 'STU00102',
    role: 'STUDENT',
    department: 'Aluno Think Green',
    status: 'ACTIVE',
    permissions: ['access_lms_student', 'submit_assignment', 'view_own_financials'],
    createdAt: '2026-02-12',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'user_student_3',
    name: 'Youssef Ali',
    email: 'youssef.ali@student.thinkgreen.org',
    studentId: 'STU00045',
    role: 'STUDENT',
    department: 'Aluno Think Green (Com Pendência)',
    status: 'ACTIVE',
    permissions: ['access_lms_student', 'submit_assignment', 'view_own_financials'],
    createdAt: '2026-02-15',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_COURSES: Course[] = [
  {
    id: 'course_eng',
    code: 'ENG-100',
    name: 'Curso Livre de Inglês',
    category: 'ENGLISH',
    description: 'Programa intensivo e conversacional de língua inglesa com metodologia comunicativa do Centro.',
    color: '#7C3AED',
    monthlyFee: 500,
    totalHours: 60,
    isActive: true,
  },
  {
    id: 'course_preschool',
    code: 'PRE-200',
    name: 'Pré-Escola Comunitária',
    category: 'PRESCHOOL',
    description: 'Educação infantil, desenvolvimento socioemocional, bilinguismo precoce e artes.',
    color: '#F97316',
    monthlyFee: 750,
    totalHours: 120,
    isActive: true,
  },
  {
    id: 'course_football',
    code: 'SPO-300',
    name: 'Academia de Futebol Think Green',
    category: 'FOOTBALL',
    description: 'Treinamento de futebol de alto rendimento, disciplina tática, saúde física e trabalho em equipe.',
    color: '#16A34A',
    monthlyFee: 400,
    totalHours: 48,
    isActive: true,
  },
  {
    id: 'course_women_fit',
    code: 'FIT-400',
    name: 'Academia & Treinos para Mulheres',
    category: 'WOMENS_FITNESS',
    description: 'Programa exclusivo de fortalecimento funcional, condicionamento aeróbico e bem-estar comunitário feminino.',
    color: '#DB2777',
    monthlyFee: 450,
    totalHours: 40,
    isActive: true,
  },
];

export const INITIAL_CLASSES: ClassRoom[] = [
  {
    id: 'class_soccer',
    courseId: 'course_football',
    name: 'Soccer Class - 8º Ano A',
    code: 'SOC-8A',
    teacherId: 'user_teacher_1',
    teacherName: 'Professor Lucas',
    schedule: 'Segunda & Quarta, 19:00 - 19:50',
    room: 'Campo Sintético Principal',
    maxCapacity: 35,
    startDate: '2026-02-01',
    endDate: '2026-11-30',
    status: 'ACTIVE',
  },
  {
    id: 'class_eng_a',
    courseId: 'course_eng',
    name: 'English Class - 7º Ano B',
    code: 'ENG-7B',
    teacherId: 'user_teacher_1',
    teacherName: 'Professor Lucas',
    schedule: 'Segunda & Quarta, 20:00 - 20:50',
    room: 'Sala 01 - Bloco Acadêmico',
    maxCapacity: 30,
    startDate: '2026-02-01',
    endDate: '2026-11-30',
    status: 'ACTIVE',
  },
  {
    id: 'class_reading',
    courseId: 'course_eng',
    name: 'Reading Class - 6º Ano C',
    code: 'READ-6C',
    teacherId: 'user_teacher_1',
    teacherName: 'Professor Lucas',
    schedule: 'Terça & Quinta, 18:00 - 18:50',
    room: 'Sala 03 - Biblioteca',
    maxCapacity: 30,
    startDate: '2026-02-01',
    endDate: '2026-11-30',
    status: 'ACTIVE',
  },
  {
    id: 'class_eng_b',
    courseId: 'course_eng',
    name: 'Inglês Intermediário B (Conversation)',
    code: 'ENG-B1-B',
    teacherId: 'user_teacher_1',
    teacherName: 'Professor Lucas',
    schedule: 'Terça & Quinta, 18:30 - 20:00',
    room: 'Sala 02 - Bloco Acadêmico',
    maxCapacity: 20,
    startDate: '2026-02-01',
    endDate: '2026-06-30',
    status: 'ACTIVE',
  },
  {
    id: 'class_preschool_a',
    courseId: 'course_preschool',
    name: 'Turma Girassol (4 a 5 anos)',
    code: 'PRE-SUN-01',
    teacherId: 'user_teacher_1',
    teacherName: 'Profª. Sarah Johnson',
    schedule: 'Segunda a Quinta, 09:00 - 12:00',
    room: 'Espaço Kids & Criatividade',
    maxCapacity: 18,
    startDate: '2026-02-01',
    endDate: '2026-11-30',
    status: 'ACTIVE',
  },
  {
    id: 'class_football_sub15',
    courseId: 'course_football',
    name: 'Futebol Juvenil Sub-15',
    code: 'FUT-SUB15',
    teacherId: 'user_teacher_2',
    teacherName: 'Prof. Tarek Mansour',
    schedule: 'Sábado & Domingo, 08:30 - 10:30',
    room: 'Campo Principal Think Green',
    maxCapacity: 30,
    startDate: '2026-02-01',
    endDate: '2026-11-30',
    status: 'ACTIVE',
  },
  {
    id: 'class_women_circuit',
    courseId: 'course_women_fit',
    name: 'Circuito Funcional Feminino - Manhã',
    code: 'FIT-CIR-M',
    teacherId: 'user_teacher_1',
    teacherName: 'Profª. Sarah Johnson',
    schedule: 'Segunda, Quarta & Sexta, 08:00 - 09:00',
    room: 'Ginásio Comunitário',
    maxCapacity: 20,
    startDate: '2026-02-01',
    endDate: '2026-08-31',
    status: 'ACTIVE',
  },
];

export const INITIAL_STUDENTS: Student[] = [
  {
    id: 'stu_1',
    studentId: 'STU00184',
    name: 'Ahmed Mohamed',
    email: 'ahmed.m@student.thinkgreen.org',
    phone: '+20 10 1234 5678',
    nationalId: '29801010101234',
    birthDate: '2004-05-14',
    guardianName: 'Mohamed Ibrahim',
    guardianPhone: '+20 10 9988 7766',
    address: 'Nasr City, Distrito 7',
    city: 'Cairo',
    status: 'ATIVO',
    notes: 'Excelente participação. Bolsista comunitário 20%.',
    createdAt: '2026-01-20',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    documents: [
      {
        id: 'doc_1',
        title: 'Documento Nacional (Cartão ID)',
        type: 'ID_CARD',
        url: '#',
        uploadedAt: '2026-01-20',
        uploadedBy: 'Mona Abdelrahman',
        size: '1.4 MB',
      },
      {
        id: 'doc_2',
        title: 'Ficha de Matrícula Assinada',
        type: 'REGISTRATION_FORM',
        url: '#',
        uploadedAt: '2026-01-20',
        uploadedBy: 'Mona Abdelrahman',
        size: '850 KB',
      },
    ],
  },
  {
    id: 'stu_2',
    studentId: 'STU00102',
    name: 'Mariam Youssef',
    email: 'mariam.y@student.thinkgreen.org',
    phone: '+20 11 2345 6789',
    nationalId: '29904040202345',
    birthDate: '2001-08-22',
    address: 'Zamalek, Rua 26 de Julho',
    city: 'Cairo',
    status: 'ATIVO',
    notes: 'Matriculada em Inglês Avançado e Circuito Feminino.',
    createdAt: '2026-01-22',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    documents: [
      {
        id: 'doc_3',
        title: 'Atestado Médico Esportivo',
        type: 'MEDICAL',
        url: '#',
        uploadedAt: '2026-01-22',
        uploadedBy: 'Mona Abdelrahman',
        size: '2.1 MB',
      },
    ],
  },
  {
    id: 'stu_3',
    studentId: 'STU00045',
    name: 'Youssef Ali',
    email: 'youssef.ali@student.thinkgreen.org',
    phone: '+20 12 3456 7890',
    nationalId: '30005050303456',
    birthDate: '2005-11-03',
    guardianName: 'Ali Mahmoud',
    guardianPhone: '+20 12 8877 6655',
    address: 'Maadi, Degla',
    city: 'Cairo',
    status: 'ATIVO',
    notes: 'Aluno com 2ª parcela pendente para teste de validação de regras de bloqueio de prova.',
    createdAt: '2026-01-25',
    avatarUrl: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    documents: [],
  },
  {
    id: 'stu_4',
    studentId: 'STU00001',
    name: 'Layla Ibrahim',
    email: 'layla.i@student.thinkgreen.org',
    phone: '+20 10 5555 4444',
    city: 'Giza',
    status: 'ATIVO',
    notes: 'Pré-Escola & Artes.',
    createdAt: '2026-01-10',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    documents: [],
  },
  {
    id: 'stu_5',
    studentId: 'STU00002',
    name: 'Omar Hassan',
    email: 'omar.h@student.thinkgreen.org',
    phone: '+20 11 9999 8888',
    city: 'Alexandria',
    status: 'ATIVO',
    notes: 'Futebol Sub-15.',
    createdAt: '2026-01-12',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    documents: [],
  },
  {
    id: 'stu_6',
    studentId: 'STU00003',
    name: 'Fatima El-Sayed',
    email: 'fatima.s@student.thinkgreen.org',
    phone: '+20 12 1111 2222',
    city: 'Cairo',
    status: 'ATIVO',
    notes: 'Inglês Básico.',
    createdAt: '2026-01-14',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    documents: [],
  },
];

export const INITIAL_ENROLLMENTS: Enrollment[] = [
  // Ahmed Mohamed (STU00184) has 2 enrollments (English + Football)
  {
    id: 'enr_1',
    studentId: 'STU00184',
    studentInternalId: 'stu_1',
    studentName: 'Ahmed Mohamed',
    courseId: 'course_eng',
    courseName: 'Curso Livre de Inglês',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    enrollmentDate: '2026-02-01',
    status: 'ATIVA',
    paymentPlan: {
      installmentsCount: 4,
      totalAmount: 2000,
      installmentAmount: 500,
    },
  },
  {
    id: 'enr_2',
    studentId: 'STU00184',
    studentInternalId: 'stu_1',
    studentName: 'Ahmed Mohamed',
    courseId: 'course_football',
    courseName: 'Academia de Futebol Think Green',
    classId: 'class_football_sub15',
    className: 'Futebol Juvenil Sub-15',
    enrollmentDate: '2026-02-05',
    status: 'ATIVA',
    paymentPlan: {
      installmentsCount: 4,
      totalAmount: 1600,
      installmentAmount: 400,
    },
  },
  // Mariam Youssef (STU00102) has 2 enrollments (English + Women's Fitness)
  {
    id: 'enr_3',
    studentId: 'STU00102',
    studentInternalId: 'stu_2',
    studentName: 'Mariam Youssef',
    courseId: 'course_eng',
    courseName: 'Curso Livre de Inglês',
    classId: 'class_eng_b',
    className: 'Inglês Intermediário B (Conversation)',
    enrollmentDate: '2026-02-01',
    status: 'ATIVA',
    paymentPlan: {
      installmentsCount: 4,
      totalAmount: 2000,
      installmentAmount: 500,
    },
  },
  {
    id: 'enr_4',
    studentId: 'STU00102',
    studentInternalId: 'stu_2',
    studentName: 'Mariam Youssef',
    courseId: 'course_women_fit',
    courseName: 'Academia & Treinos para Mulheres',
    classId: 'class_women_circuit',
    className: 'Circuito Funcional Feminino - Manhã',
    enrollmentDate: '2026-02-03',
    status: 'ATIVA',
    paymentPlan: {
      installmentsCount: 4,
      totalAmount: 1800,
      installmentAmount: 450,
    },
  },
  // Youssef Ali (STU00045) has 1 enrollment (English with pending 2nd installment)
  {
    id: 'enr_5',
    studentId: 'STU00045',
    studentInternalId: 'stu_3',
    studentName: 'Youssef Ali',
    courseId: 'course_eng',
    courseName: 'Curso Livre de Inglês',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    enrollmentDate: '2026-02-01',
    status: 'ATIVA',
    paymentPlan: {
      installmentsCount: 4,
      totalAmount: 2000,
      installmentAmount: 500,
    },
  },
  // Layla Ibrahim (STU00001)
  {
    id: 'enr_6',
    studentId: 'STU00001',
    studentInternalId: 'stu_4',
    studentName: 'Layla Ibrahim',
    courseId: 'course_preschool',
    courseName: 'Pré-Escola Comunitária',
    classId: 'class_preschool_a',
    className: 'Turma Girassol (4 a 5 anos)',
    enrollmentDate: '2026-02-01',
    status: 'ATIVA',
    paymentPlan: {
      installmentsCount: 4,
      totalAmount: 3000,
      installmentAmount: 750,
    },
  },
  // Omar Hassan (STU00002)
  {
    id: 'enr_7',
    studentId: 'STU00002',
    studentInternalId: 'stu_5',
    studentName: 'Omar Hassan',
    courseId: 'course_football',
    courseName: 'Academia de Futebol Think Green',
    classId: 'class_football_sub15',
    className: 'Futebol Juvenil Sub-15',
    enrollmentDate: '2026-02-01',
    status: 'ATIVA',
    paymentPlan: {
      installmentsCount: 4,
      totalAmount: 1600,
      installmentAmount: 400,
    },
  },
];

export const INITIAL_CHARGES: Charge[] = [
  // Ahmed Mohamed - English (Installment 1 PAID, 2 PAID, 3 PENDENTE, 4 PENDENTE)
  {
    id: 'chg_1_1',
    enrollmentId: 'enr_1',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 1,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-02-05',
    status: 'PAGO',
    paidAmount: 500,
    paidAt: '2026-02-03 10:15',
    paymentMethod: 'DINHEIRO',
    receiptNumber: 'REC-2026-00101',
    registeredBy: 'Karim Fahmy',
    notes: '1ª Parcela - Matrícula confirmada no balcão.',
  },
  {
    id: 'chg_1_2',
    enrollmentId: 'enr_1',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 2,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-03-05',
    status: 'PAGO',
    paidAmount: 500,
    paidAt: '2026-03-01 14:30',
    paymentMethod: 'DINHEIRO',
    receiptNumber: 'REC-2026-00142',
    registeredBy: 'Karim Fahmy',
    notes: '2ª Parcela - Recebimento em dinheiro físico no balcão da secretaria.',
  },
  {
    id: 'chg_1_3',
    enrollmentId: 'enr_1',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 3,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-04-05',
    status: 'REGULAR',
  },
  {
    id: 'chg_1_4',
    enrollmentId: 'enr_1',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 4,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-05-05',
    status: 'REGULAR',
  },

  // Ahmed Mohamed - Football (Installment 1 PAID, 2 PAID)
  {
    id: 'chg_2_1',
    enrollmentId: 'enr_2',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Academia de Futebol Think Green',
    installmentNumber: 1,
    totalInstallments: 4,
    amount: 400,
    dueDate: '2026-02-05',
    status: 'PAGO',
    paidAmount: 400,
    paidAt: '2026-02-04 11:20',
    paymentMethod: 'DINHEIRO',
    receiptNumber: 'REC-2026-00109',
    registeredBy: 'Karim Fahmy',
  },
  {
    id: 'chg_2_2',
    enrollmentId: 'enr_2',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Academia de Futebol Think Green',
    installmentNumber: 2,
    totalInstallments: 4,
    amount: 400,
    dueDate: '2026-03-05',
    status: 'PAGO',
    paidAmount: 400,
    paidAt: '2026-03-02 09:00',
    paymentMethod: 'DINHEIRO',
    receiptNumber: 'REC-2026-00148',
    registeredBy: 'Karim Fahmy',
  },

  // Mariam Youssef - English & Fitness (Fully up to date)
  {
    id: 'chg_3_1',
    enrollmentId: 'enr_3',
    studentId: 'STU00102',
    studentName: 'Mariam Youssef',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 1,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-02-05',
    status: 'PAGO',
    paidAmount: 500,
    paidAt: '2026-02-01 16:40',
    paymentMethod: 'CARTAO',
    receiptNumber: 'REC-2026-00088',
    registeredBy: 'Karim Fahmy',
  },
  {
    id: 'chg_3_2',
    enrollmentId: 'enr_3',
    studentId: 'STU00102',
    studentName: 'Mariam Youssef',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 2,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-03-05',
    status: 'PAGO',
    paidAmount: 500,
    paidAt: '2026-03-01 11:00',
    paymentMethod: 'CARTAO',
    receiptNumber: 'REC-2026-00139',
    registeredBy: 'Karim Fahmy',
  },

  // Youssef Ali (STU00045) - 1st paid, but 2nd PENDENTE / EM ATRASO! (Gate 2 will trigger locked exam)
  {
    id: 'chg_5_1',
    enrollmentId: 'enr_5',
    studentId: 'STU00045',
    studentName: 'Youssef Ali',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 1,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-02-05',
    status: 'PAGO',
    paidAmount: 500,
    paidAt: '2026-02-02 12:00',
    paymentMethod: 'DINHEIRO',
    receiptNumber: 'REC-2026-00095',
    registeredBy: 'Karim Fahmy',
  },
  {
    id: 'chg_5_2',
    enrollmentId: 'enr_5',
    studentId: 'STU00045',
    studentName: 'Youssef Ali',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 2,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-03-01',
    status: 'EM ATRASO',
    notes: 'Aguardando confirmação. Pendência bloqueia Prova 1 até quitação.',
  },
  {
    id: 'chg_5_3',
    enrollmentId: 'enr_5',
    studentId: 'STU00045',
    studentName: 'Youssef Ali',
    courseName: 'Curso Livre de Inglês',
    installmentNumber: 3,
    totalInstallments: 4,
    amount: 500,
    dueDate: '2026-04-05',
    status: 'REGULAR',
  },
];

export const INITIAL_RECEIPTS: PaymentReceipt[] = [
  {
    id: 'rec_1',
    receiptNumber: 'REC-2026-00101',
    chargeId: 'chg_1_1',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Curso Livre de Inglês',
    amount: 500,
    paymentMethod: 'DINHEIRO',
    installmentDescription: 'Parcela 01/04 - Matrícula e Mensalidade Fevereiro',
    date: '2026-02-03 10:15',
    issuedBy: 'Karim Fahmy (Tesouraria)',
    notes: 'Recibo oficial emitido pelo Think Green Community Center - Cairo.',
  },
  {
    id: 'rec_2',
    receiptNumber: 'REC-2026-00142',
    chargeId: 'chg_1_2',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Curso Livre de Inglês',
    amount: 500,
    paymentMethod: 'DINHEIRO',
    installmentDescription: 'Parcela 02/04 - Mensalidade Março',
    date: '2026-03-01 14:30',
    issuedBy: 'Karim Fahmy (Tesouraria)',
    notes: 'Recebido em dinheiro em espécie no balcão da secretaria. Prova 1 liberada no sistema acadêmico.',
  },
  {
    id: 'rec_3',
    receiptNumber: 'REC-2026-00109',
    chargeId: 'chg_2_1',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    courseName: 'Academia de Futebol Think Green',
    amount: 400,
    paymentMethod: 'DINHEIRO',
    installmentDescription: 'Parcela 01/04 - Futebol Fevereiro',
    date: '2026-02-04 11:20',
    issuedBy: 'Karim Fahmy (Tesouraria)',
  },
  {
    id: 'rec_4',
    receiptNumber: 'REC-2026-00088',
    chargeId: 'chg_3_1',
    studentId: 'STU00102',
    studentName: 'Mariam Youssef',
    courseName: 'Curso Livre de Inglês',
    amount: 500,
    paymentMethod: 'CARTAO',
    installmentDescription: 'Parcela 01/04 - Fevereiro',
    date: '2026-02-01 16:40',
    issuedBy: 'Karim Fahmy (Tesouraria)',
  },
  {
    id: 'rec_5',
    receiptNumber: 'REC-2026-00095',
    chargeId: 'chg_5_1',
    studentId: 'STU00045',
    studentName: 'Youssef Ali',
    courseName: 'Curso Livre de Inglês',
    amount: 500,
    paymentMethod: 'DINHEIRO',
    installmentDescription: 'Parcela 01/04 - Fevereiro',
    date: '2026-02-02 12:00',
    issuedBy: 'Karim Fahmy (Tesouraria)',
  },
];

export const INITIAL_CASH_REGISTERS: CashRegister[] = [
  {
    id: 'cash_reg_current',
    operatorId: 'user_fin',
    operatorName: 'Karim Fahmy',
    openingDate: '2026-03-01 08:30',
    initialBalance: 1000,
    totalIn: 1800,
    totalOut: 200,
    expectedBalance: 2600,
    status: 'ABERTO',
    notes: 'Caixa de atendimento principal da recepção / tesouraria.',
  },
];

export const INITIAL_CASH_MOVEMENTS: CashMovement[] = [
  {
    id: 'mov_1',
    cashRegisterId: 'cash_reg_current',
    type: 'ENTRADA',
    category: 'Recebimento de Mensalidade',
    amount: 500,
    description: 'Pagamento de Ahmed Mohamed (STU00184) - Inglês',
    relatedPaymentReceipt: 'REC-2026-00101',
    timestamp: '2026-03-01 09:15',
    operatorName: 'Karim Fahmy',
  },
  {
    id: 'mov_2',
    cashRegisterId: 'cash_reg_current',
    type: 'ENTRADA',
    category: 'Recebimento de Mensalidade',
    amount: 400,
    description: 'Pagamento de Ahmed Mohamed (STU00184) - Futebol',
    relatedPaymentReceipt: 'REC-2026-00148',
    timestamp: '2026-03-01 10:45',
    operatorName: 'Karim Fahmy',
  },
  {
    id: 'mov_3',
    cashRegisterId: 'cash_reg_current',
    type: 'SAIDA',
    category: 'Material de Escritório & Limpeza',
    amount: 200,
    description: 'Compra emergencial de papel A4 e suprimentos para as salas de aula',
    timestamp: '2026-03-01 11:30',
    operatorName: 'Karim Fahmy',
  },
  {
    id: 'mov_4',
    cashRegisterId: 'cash_reg_current',
    type: 'ENTRADA',
    category: 'Recebimento de Mensalidade',
    amount: 900,
    description: 'Pagamentos avulsos de alunos de Pré-Escola',
    timestamp: '2026-03-01 13:00',
    operatorName: 'Karim Fahmy',
  },
];

export const INITIAL_ASSESSMENTS: Assessment[] = [
  {
    id: 'asm_soc_1',
    classId: 'class_soccer',
    className: 'Soccer Class - 8º Ano A',
    courseName: 'Academia de Futebol Think Green',
    title: 'Prova Prática 01 - Fundamentos Técnicos & Tática Coletiva',
    type: 'PROVA_1',
    date: '2026-03-24',
    time: '19:00',
    maxScore: 100,
    weight: 40,
    requiredPaymentStage: 'STAGE_2_PAID',
    description: 'Avaliação prática de passe, domínio orientado, finalização e posicionamento em campo.',
    content: 'Unidade 1: Domínio orientado e condução em velocidade.\nUnidade 2: Linhas de passe e triangulações táticas (4-3-3).\nUnidade 3: Transição defensiva e marcação por zona.\nUnidade 4: Finalização com ambos os pés.',
    instructions: 'Os alunos devem comparecer devidamente uniformizados com chuteira society e caneleira. Aquecimento obrigatório 15 min antes.',
    status: 'AGENDADA',
  },
  {
    id: 'asm_soc_final',
    classId: 'class_soccer',
    className: 'Soccer Class - 8º Ano A',
    courseName: 'Academia de Futebol Think Green',
    title: 'Exame Final & Torneio Integrador Think Garden',
    type: 'PROVA_FINAL',
    date: '2026-06-18',
    time: '19:00',
    maxScore: 100,
    weight: 50,
    requiredPaymentStage: 'STAGE_FINAL_PAID',
    description: 'Torneio de encerramento do semestre com avaliação individual de performance, disciplina e fair play.',
    content: 'Aplicação prática de todos os fundamentos trabalhados no semestre, tomada de decisão sob pressão e espírito de equipe.',
    instructions: 'Avaliação contínua durante as partidas oficiais do torneio interno.',
    status: 'AGENDADA',
  },
  {
    id: 'asm_eng_1',
    classId: 'class_eng_a',
    className: 'English Class - 7º Ano B',
    courseName: 'Curso Livre de Inglês',
    title: 'Midterm Exam - Grammar & Oral Communication (Prova 1)',
    type: 'PROVA_1',
    date: '2026-03-25',
    time: '20:00',
    maxScore: 100,
    weight: 35,
    requiredPaymentStage: 'STAGE_2_PAID', // Rule 2: Requires 2nd installment paid!
    description: 'Avaliação presencial de gramática, vocabulário e diálogo em pares.',
    content: 'Capítulo 1: Simple Present & Daily Routines in Cairo.\nCapítulo 2: Adverbs of Frequency (always, usually, never).\nCapítulo 3: Present Continuous & Active Actions.\nCapítulo 4: Oral Dialogues: Market and Community Center scenarios.',
    instructions: 'Prova individual sem consulta a materiais. Duração de 50 minutos. Trazer caneta azul ou preta.',
    status: 'AGENDADA',
  },
  {
    id: 'asm_eng_final',
    classId: 'class_eng_a',
    className: 'English Class - 7º Ano B',
    courseName: 'Curso Livre de Inglês',
    title: 'Final Examination & Certification Project (Prova Final)',
    type: 'PROVA_FINAL',
    date: '2026-06-20',
    time: '20:00',
    maxScore: 100,
    weight: 45,
    requiredPaymentStage: 'STAGE_FINAL_PAID', // Rule 3: Requires full payment
    description: 'Exame final de proficiência e apresentação de projeto do Centro.',
    content: 'Conteúdo integral do nível A1/A2: Verbos regulares/irregulares no Simple Past, Wh-questions, leitura de textos e redação temática de 150 palavras.',
    instructions: 'Apresentação oral em duplas (10 min) seguida de prova escrita dissertativa.',
    status: 'AGENDADA',
  },
  {
    id: 'asm_eng_quiz',
    classId: 'class_eng_a',
    className: 'English Class - 7º Ano B',
    courseName: 'Curso Livre de Inglês',
    title: 'Quiz 01 - Present Simple & Daily Routines',
    type: 'QUIZ',
    date: '2026-02-20',
    time: '20:00',
    maxScore: 100,
    weight: 20,
    requiredPaymentStage: 'STAGE_1_PAID', // Rule 1: Requires 1st installment
    description: 'Quiz formativo de fixação.',
    content: '15 questões objetivas de múltipla escolha e preenchimento de lacunas sobre rotinas diárias e conjugação do Simple Present.',
    instructions: 'Tempo máximo de resolução: 25 minutos.',
    status: 'CONCLUIDA',
  },
  {
    id: 'asm_read_1',
    classId: 'class_reading',
    className: 'Reading Class - 6º Ano C',
    courseName: 'Curso Livre de Inglês',
    title: 'Prova 1 - Interpretação Textual & Vocabulário Contextual',
    type: 'PROVA_1',
    date: '2026-03-27',
    time: '18:00',
    maxScore: 100,
    weight: 40,
    requiredPaymentStage: 'STAGE_2_PAID',
    description: 'Leitura comentada de contos curtos e análise crítica de personagens.',
    content: 'Contos: "The Think Green Garden Story" e "Adventures in the Nile Delta".\nAnálise de elementos narrativos: enredo, clímax, desfecho e vocabulário chave.',
    instructions: 'Permitido o uso do dicionário bilíngue nos primeiros 15 minutos.',
    status: 'AGENDADA',
  },
  {
    id: 'asm_eng_b1',
    classId: 'class_eng_b',
    className: 'Inglês Intermediário B (Conversation)',
    courseName: 'Curso Livre de Inglês',
    title: 'Speaking & Debate Presentation (Prova 1)',
    type: 'PROVA_1',
    date: '2026-03-26',
    time: '18:30',
    maxScore: 100,
    weight: 40,
    requiredPaymentStage: 'STAGE_2_PAID',
    content: 'Debate temático: Sustentabilidade e Juventude Urbana.',
    instructions: 'Apresentação em formato pitch de 5 minutos.',
    status: 'AGENDADA',
  },
];

export const INITIAL_GRADES: Grade[] = [
  {
    id: 'grd_1',
    assessmentId: 'asm_eng_quiz',
    assessmentTitle: 'Quiz 01 - Present Simple & Daily Routines',
    classId: 'class_eng_a',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    score: 92,
    maxScore: 100,
    percentage: 92,
    feedback: 'Excelente domínio das estruturas verbais e pronúncia clara!',
    gradedAt: '2026-02-22',
    gradedBy: 'Profª. Sarah Johnson',
  },
  {
    id: 'grd_2',
    assessmentId: 'asm_eng_quiz',
    assessmentTitle: 'Quiz 01 - Present Simple & Daily Routines',
    classId: 'class_eng_a',
    studentId: 'STU00045',
    studentName: 'Youssef Ali',
    score: 78,
    maxScore: 100,
    percentage: 78,
    feedback: 'Bom desempenho. Revisar uso de terceira pessoa (he/she/it).',
    gradedAt: '2026-02-22',
    gradedBy: 'Profª. Sarah Johnson',
  },
  {
    id: 'grd_3',
    assessmentId: 'asm_eng_b1',
    assessmentTitle: 'Speaking & Debate Presentation (Prova 1)',
    classId: 'class_eng_b',
    studentId: 'STU00102',
    studentName: 'Mariam Youssef',
    score: 95,
    maxScore: 100,
    percentage: 95,
    feedback: 'Argumentação fluente e vocabulário avançado na temática ambiental.',
    gradedAt: '2026-03-27',
    gradedBy: 'Profª. Sarah Johnson',
  },
  {
    id: 'grd_4',
    assessmentId: 'asm_fut_eval',
    assessmentTitle: 'Avaliação Tática & Teste de Resistência Física',
    classId: 'class_football_sub15',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    score: 88,
    maxScore: 100,
    percentage: 88,
    feedback: 'Excelente visão de jogo como meio-campo e dedicação nos treinos.',
    gradedAt: '2026-03-16',
    gradedBy: 'Prof. Tarek Mansour',
  },
];

export const INITIAL_LESSONS: Lesson[] = [
  {
    id: 'les_1',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    title: 'Aula 08: Introdução às Conversas do Cotidiano & Comunidade',
    description: 'Prática de diálogos no mercado local, cumprimentos formais e informais, e vocabulário do Centro Comunitário.',
    date: '2026-03-02',
    teacherId: 'user_teacher_1',
    teacherName: 'Profª. Sarah Johnson',
    videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    materials: [
      {
        id: 'mat_1',
        title: 'Apostila da Aula 08 - Everyday Dialogues.pdf',
        type: 'PDF',
        url: '#',
        size: '2.4 MB',
      },
      {
        id: 'mat_2',
        title: 'Áudio de Prática de Pronúncia (Listening mp3)',
        type: 'AUDIO',
        url: '#',
        size: '5.1 MB',
      },
      {
        id: 'mat_3',
        title: 'Guia de Estudo de Vocabulário Think Green',
        type: 'DOC',
        url: '#',
        size: '420 KB',
      },
    ],
  },
  {
    id: 'les_2',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    title: 'Aula 07: Present Continuous & Ações em Andamento',
    description: 'Estruturas de sujeito + to be + verbo com -ing. Exercícios em grupo com cartões de imagens.',
    date: '2026-02-25',
    teacherId: 'user_teacher_1',
    teacherName: 'Profª. Sarah Johnson',
    materials: [
      {
        id: 'mat_4',
        title: 'Slides da Aula 07 - Present Continuous.pdf',
        type: 'PDF',
        url: '#',
        size: '3.1 MB',
      },
    ],
  },
  {
    id: 'les_3',
    classId: 'class_football_sub15',
    className: 'Futebol Juvenil Sub-15',
    title: 'Treino Tático 06: Transição Ofensiva & Compactação Defensiva',
    description: 'Exercícios no campo principal com foco em passes em profundidade e recomposição rápida.',
    date: '2026-03-01',
    teacherId: 'user_teacher_2',
    teacherName: 'Prof. Tarek Mansour',
    materials: [
      {
        id: 'mat_5',
        title: 'Esquema Tático Sub-15 - Prancheta Think Green.pdf',
        type: 'PDF',
        url: '#',
        size: '1.2 MB',
      },
    ],
  },
  {
    id: 'les_4',
    classId: 'class_women_circuit',
    className: 'Circuito Funcional Feminino - Manhã',
    title: 'Sessão 12: Fortalecimento Postural e Treino de Alta Intensidade',
    description: 'Sequência de exercícios corporais, alongamento dinâmico e respiração guiada.',
    date: '2026-03-02',
    teacherId: 'user_teacher_1',
    teacherName: 'Profª. Sarah Johnson',
    materials: [
      {
        id: 'mat_6',
        title: 'Guia de Alongamento e Hidratação.pdf',
        type: 'PDF',
        url: '#',
        size: '1.8 MB',
      },
    ],
  },
];

export const INITIAL_ASSIGNMENTS: Assignment[] = [
  {
    id: 'asg_1',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    title: 'Tarefa 04: Redação "My Community and Daily Routine"',
    instructions: 'Escreva um texto de 80 a 120 palavras descrevendo sua rotina diária no Cairo e como você participa das atividades do Think Green Community Center. Utilize verbos no Present Simple.',
    dueDate: '2026-03-10',
    maxScore: 100,
    teacherName: 'Profª. Sarah Johnson',
    category: 'REDACAO',
  },
  {
    id: 'asg_2',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    title: 'Exercício 05: Diálogos no Mercado & Vocabulário Cotidiano',
    instructions: 'Complete as 10 frases com as preposições de lugar e verbos de ação adequados com base no áudio da Aula 08.',
    dueDate: '2026-03-15',
    maxScore: 100,
    teacherName: 'Profª. Sarah Johnson',
    category: 'EXERCICIO',
  },
  {
    id: 'asg_3',
    classId: 'class_soccer',
    className: 'Soccer Class - 8º Ano A',
    title: 'Análise de Posicionamento & Compactação Tática',
    instructions: 'Assistir ao vídeo de 5 minutos sobre compactação defensiva e responder às 3 perguntas sobre a função do volante de transição.',
    dueDate: '2026-03-12',
    maxScore: 100,
    teacherName: 'Profª. Sarah Johnson',
    category: 'PRATICA',
  },
  {
    id: 'asg_4',
    classId: 'class_football_sub15',
    className: 'Futebol Juvenil Sub-15',
    title: 'Diário de Treino & Hábitos de Sono',
    instructions: 'Registre suas 7 noites de descanso e hidratação pré e pós-treino da semana para acompanhamento com a equipe física.',
    dueDate: '2026-03-08',
    maxScore: 100,
    teacherName: 'Prof. Tarek Mansour',
    category: 'DIARIO',
  },
  {
    id: 'asg_5',
    classId: 'class_reading',
    className: 'Reading Class - 6º Ano C',
    title: 'Ficha de Leitura: Capítulo 3 do Livro O Pequeno Príncipe',
    instructions: 'Resumo reflexivo destacando a metáfora dos baobás e a responsabilidade com o meio ambiente comunitário.',
    dueDate: '2026-03-14',
    maxScore: 100,
    teacherName: 'Profª. Sarah Johnson',
    category: 'REDACAO',
  },
];

export const INITIAL_SUBMISSIONS: Submission[] = [
  {
    id: 'sub_1',
    assignmentId: 'asg_1',
    assignmentTitle: 'Tarefa 04: Redação "My Community and Daily Routine"',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    submissionText: 'I wake up at 7:00 AM every day. After breakfast, I study English and in the afternoon I go to the Think Green Center to play football with my team. It helps my community and keeps me active!',
    attachmentName: 'My_Community_Essay_Ahmed.pdf',
    submittedAt: '2026-03-03 14:20',
    status: 'VISTO',
    score: 95,
    maxScore: 100,
    feedback: 'Parabéns Ahmed! O texto está muito bem estruturado e com uso correto de conectores e tempos verbais. Visto com louvor!',
    gradedAt: '2026-03-03 18:00',
    gradedBy: 'Profª. Sarah Johnson',
    deliveryMethod: 'ONLINE',
  },
  {
    id: 'sub_2',
    assignmentId: 'asg_1',
    assignmentTitle: 'Tarefa 04: Redação "My Community and Daily Routine"',
    studentId: 'STU00045',
    studentName: 'Youssef Ali',
    submissionText: 'My routine starts with school in morning. Then I help my family in shop and come to English class at 4 PM to learn new words and grammar.',
    attachmentName: 'Youssef_Routine_Draft.docx',
    submittedAt: '2026-03-04 09:15',
    status: 'PENDENTE_CORRECAO',
    maxScore: 100,
    deliveryMethod: 'ONLINE',
  },
  {
    id: 'sub_3',
    assignmentId: 'asg_3',
    assignmentTitle: 'Análise de Posicionamento & Compactação Tática',
    studentId: 'STU00184',
    studentName: 'Ahmed Mohamed',
    submissionText: 'O volante deve manter a linha média fechada e cobrir o lateral quando houver inversão de jogada rápida pelo flanco oposto.',
    submittedAt: '2026-03-04 11:30',
    status: 'VISTO',
    score: 100,
    maxScore: 100,
    feedback: 'Excelente leitura tática! Aplicaremos este conceito no treino prático de quinta-feira.',
    gradedAt: '2026-03-04 14:00',
    gradedBy: 'Profª. Sarah Johnson',
    deliveryMethod: 'ONLINE',
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att_1',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    date: '2026-03-02',
    teacherId: 'user_teacher_1',
    teacherName: 'Profª. Sarah Johnson',
    students: [
      { studentId: 'STU00184', studentName: 'Ahmed Mohamed', present: true },
      { studentId: 'STU00045', studentName: 'Youssef Ali', present: true },
      { studentId: 'STU00003', studentName: 'Fatima El-Sayed', present: true },
    ],
    notes: 'Todos os alunos presentes pontualmente. Participação ativa no diálogo oral.',
    savedAt: '2026-03-02 18:35',
  },
  {
    id: 'att_2',
    classId: 'class_eng_a',
    className: 'Inglês Básico A (Beginners)',
    date: '2026-02-25',
    teacherId: 'user_teacher_1',
    teacherName: 'Profª. Sarah Johnson',
    students: [
      { studentId: 'STU00184', studentName: 'Ahmed Mohamed', present: true },
      { studentId: 'STU00045', studentName: 'Youssef Ali', present: false, justified: true, note: 'Consulta médica comunicada' },
      { studentId: 'STU00003', studentName: 'Fatima El-Sayed', present: true },
    ],
    savedAt: '2026-02-25 18:30',
  },
  {
    id: 'att_3',
    classId: 'class_football_sub15',
    className: 'Futebol Juvenil Sub-15',
    date: '2026-03-01',
    teacherId: 'user_teacher_2',
    teacherName: 'Prof. Tarek Mansour',
    students: [
      { studentId: 'STU00184', studentName: 'Ahmed Mohamed', present: true },
      { studentId: 'STU00002', studentName: 'Omar Hassan', present: true },
    ],
    savedAt: '2026-03-01 10:35',
  },
];

export const INITIAL_ACCOUNTING_TRANSACTIONS: AccountingTransaction[] = [
  {
    id: 'acc_tx_1',
    type: 'RECEITA',
    amount: 14500,
    date: '2026-02-28',
    category: 'Mensalidades - Curso de Inglês',
    costCenter: 'Centro Acadêmico de Idiomas',
    description: 'Consolidação de mensalidades de Fevereiro do Curso Livre de Inglês (29 alunos)',
    status: 'CONCILIADO',
    registeredBy: 'Hisham El-Ghazaly',
  },
  {
    id: 'acc_tx_2',
    type: 'RECEITA',
    amount: 12000,
    date: '2026-02-28',
    category: 'Mensalidades - Academia de Futebol',
    costCenter: 'Esportes Comunitários',
    description: 'Consolidação de mensalidades de Fevereiro da Academia de Futebol Sub-15 e Sub-12',
    status: 'CONCILIADO',
    registeredBy: 'Hisham El-Ghazaly',
  },
  {
    id: 'acc_tx_3',
    type: 'RECEITA',
    amount: 9000,
    date: '2026-02-28',
    category: 'Mensalidades - Treinos Mulheres & Pré-Escola',
    costCenter: 'Programas Comunitários',
    description: 'Consolidação de mensalidades e inscrições',
    status: 'CONCILIADO',
    registeredBy: 'Hisham El-Ghazaly',
  },
  {
    id: 'acc_tx_4',
    type: 'DESPESA',
    amount: 11000,
    date: '2026-02-28',
    category: 'Folha de Professores & Instrutores',
    costCenter: 'Recursos Humanos',
    description: 'Remuneração dos professores de Inglês, Futebol e Instrutores do Centro',
    status: 'CONCILIADO',
    registeredBy: 'Hisham El-Ghazaly',
  },
  {
    id: 'acc_tx_5',
    type: 'DESPESA',
    amount: 3500,
    date: '2026-02-25',
    category: 'Manutenção & Energia Elétrica',
    costCenter: 'Instalações & Infraestrutura',
    description: 'Conta de energia do complexo e manutenção da iluminação dos campos',
    status: 'CONCILIADO',
    registeredBy: 'Hisham El-Ghazaly',
  },
  {
    id: 'acc_tx_6',
    type: 'DESPESA',
    amount: 2200,
    date: '2026-02-20',
    category: 'Material Didático & Esportivo',
    costCenter: 'Suprimentos Pedagógicos',
    description: 'Impressão de apostilas do Curso Livre de Inglês e bolas de futebol oficiais',
    status: 'CONCILIADO',
    registeredBy: 'Hisham El-Ghazaly',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log_1',
    timestamp: '2026-03-01 14:30:12',
    userId: 'user_fin',
    userName: 'Karim Fahmy',
    role: 'FINANCE',
    module: 'FINANCE',
    action: 'REGISTRO_PAGAMENTO',
    entityType: 'Charge',
    entityId: 'chg_1_2',
    previousValue: 'PENDENTE (500 EGP)',
    newValue: 'PAGO (500 EGP via Dinheiro em Espécie)',
    details: 'Pagamento físico de 2ª parcela de Ahmed Mohamed (STU00184) no balcão. Recibo REC-2026-00142 gerado. Prova 1 liberada no Acadêmico.',
  },
  {
    id: 'log_2',
    timestamp: '2026-03-01 10:15:00',
    userId: 'user_sec',
    userName: 'Mona Abdelrahman',
    role: 'SECRETARIAT',
    module: 'SECRETARIAT',
    action: 'CRIACAO_MATRICULA',
    entityType: 'Enrollment',
    entityId: 'enr_1',
    previousValue: 'None',
    newValue: 'Ahmed Mohamed -> Inglês Básico A (STU00184)',
    details: 'Matrícula criada com plano de 4 parcelas de 500 EGP. STU ID e cobranças automáticas geradas.',
  },
  {
    id: 'log_3',
    timestamp: '2026-02-22 16:45:00',
    userId: 'user_teacher_1',
    userName: 'Profª. Sarah Johnson',
    role: 'TEACHER',
    module: 'ACADEMIC',
    action: 'LANCAMENTO_NOTA',
    entityType: 'Grade',
    entityId: 'grd_1',
    previousValue: 'Sem Nota',
    newValue: 'Nota: 92/100',
    details: 'Nota lançada para Ahmed Mohamed (STU00184) no Quiz 01.',
  },
];

export const INITIAL_NOTIFICATIONS: SystemNotification[] = [
  {
    id: 'notif_1',
    targetRole: 'ALL',
    title: 'Bem-vindo à Nova Think Green Platform!',
    message: 'Sistema integrado de gestão do Think Green Community Center em operação com Secretaria, Financeiro, Acadêmico e AVA.',
    type: 'INFO',
    timestamp: '2026-03-01 08:00',
    read: false,
  },
  {
    id: 'notif_2',
    userId: 'user_student_1',
    targetRole: 'STUDENT',
    title: 'Pagamento Confirmado & Prova Liberada!',
    message: 'Seu pagamento de 500 EGP (2ª Parcela) foi confirmado pela tesouraria. A Prova 1 de Inglês Básico está agora liberada!',
    type: 'SUCCESS',
    timestamp: '2026-03-01 14:31',
    read: false,
  },
  {
    id: 'notif_3',
    userId: 'user_student_3',
    targetRole: 'STUDENT',
    title: 'Aviso de Pendência Financeira',
    message: 'Sua 2ª parcela de Inglês Básico está em aberto. Regularize na recepção para liberar o acesso à Prova 1.',
    type: 'WARNING',
    timestamp: '2026-03-01 10:00',
    read: false,
  },
];
